param(
    [int]$Length = 14,
    [int]$Count = 3,
    [switch]$ExcludeAmbiguous = $true,
    [switch]$CopyToClipboard
)

# Policy (tweak per client if needed)
$MinLength = 12
$RequireUpper = $true
$RequireLower = $true
$RequireDigit = $true
$RequireSpecial = $true

if ($Length -lt $MinLength) {
    Write-Host "[ERROR] Length must be at least $MinLength"
    exit 1
}

# Character sets
$upper   = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
$lower   = "abcdefghijklmnopqrstuvwxyz"
$digits  = "0123456789"
$special = "!@#$%^&*()-_=+[]{};:,.?"

if ($ExcludeAmbiguous) {
    # Remove easily confused chars
    $upper   = ($upper   -replace '[OIL]', '')
    $lower   = ($lower   -replace '[ol]', '')
    $digits  = ($digits  -replace '[01]', '')
}

function New-Password {
    param([int]$Len)

    $rand = New-Object System.Random
    $chars = @()

    if ($RequireUpper)   { $chars += $upper[$rand.Next(0, $upper.Length)] }
    if ($RequireLower)   { $chars += $lower[$rand.Next(0, $lower.Length)] }
    if ($RequireDigit)   { $chars += $digits[$rand.Next(0, $digits.Length)] }
    if ($RequireSpecial) { $chars += $special[$rand.Next(0, $special.Length)] }

    $pool = ($upper + $lower + $digits + $special).ToCharArray()

    while ($chars.Count -lt $Len) {
        $chars += $pool[$rand.Next(0, $pool.Length)]
    }

    # Shuffle
    $chars = $chars | Sort-Object {Get-Random}
    return -join $chars
}

Write-Host ""
Write-Host "======================================"
Write-Host "Password Reset Generator (Policy-Based)"
Write-Host "======================================"
Write-Host ""

$passwords = @()
for ($i=0; $i -lt $Count; $i++) {
    $passwords += New-Password -Len $Length
}

Write-Host "Generated Passwords:"
foreach ($p in $passwords) {
    Write-Host "- $p"
}

# Optional: copy first password to clipboard (Windows)
if ($CopyToClipboard) {
    try {
        Set-Clipboard -Value $passwords[0]
        Write-Host ""
        Write-Host "[OK] First password copied to clipboard."
    } catch {
        Write-Host "[WARN] Clipboard copy failed."
    }
}

# Optional audit event (no password stored)
try {
    $source = "BayouFindsOps"
    if (-not [System.Diagnostics.EventLog]::SourceExists($source)) {
        New-EventLog -LogName Application -Source $source | Out-Null
    }
    Write-EventLog -LogName Application -Source $source -EntryType Information -EventId 9001 `
        -Message "Password reset generated by $env:USERDOMAIN\$env:USERNAME on $env:COMPUTERNAME (policy enforced)."
} catch {
    # best-effort; ignore if not permitted
}
